# Generated by Django 4.1 on 2022-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Forum Kategorisi'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
