# Generated by Django 4.1 on 2022-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_forum_category_alter_forumcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
    ]
