# Generated by Django 4.1 on 2022-08-28 10:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_forumview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumview',
            options={'verbose_name_plural': '4. Forum Görüntülenmeleri'},
        ),
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Forum İçeriği'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yorum'),
        ),
    ]
