# Generated by Django 4.1 on 2022-08-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_alter_forumview_options_alter_forum_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.TextField(null=True, verbose_name='Forum İçeriği'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='content',
            field=models.TextField(null=True, verbose_name='Yorum'),
        ),
    ]
