# Generated by Django 4.1 on 2022-08-28 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0011_alter_forum_content_alter_forumcomment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='parent',
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reply_comment', to='forums.forumcomment', verbose_name='İlgili Yorum')),
                ('forums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reply_comment', to='forums.forum', verbose_name='İlgili Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum Yapan Kullanıcı')),
            ],
        ),
    ]
