# Generated by Django 4.1 on 2022-08-28 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0012_remove_forumcomment_parent_replycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumview',
            options={'verbose_name_plural': '6. Forum Görüntülenmeleri'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'verbose_name_plural': '4. Yorum Yanıtları'},
        ),
        migrations.CreateModel(
            name='TwoLevelReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_tworeply_comment', to='forums.forumcomment', verbose_name='İlgili Ana Yorum')),
                ('forums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_tworeply_comment', to='forums.forum', verbose_name='İlgili Forum')),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_tworeply_comment', to='forums.replycomment', verbose_name='İlgili İkinci Yorum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum Yapan Kullanıcı')),
            ],
            options={
                'verbose_name_plural': '5. Yorum Yanıtları',
            },
        ),
    ]
