# Generated by Django 4.1 on 2022-08-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_alter_forumview_options_alter_replycomment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoLevelReplyComment',
        ),
    ]
