# Generated by Django 4.1 on 2022-08-29 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0016_alter_likeforum_options_alter_likeforum_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_liked', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to='forums.forumcomment', verbose_name='İlgili Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to=settings.AUTH_USER_MODEL, verbose_name='Beğenen Kullanıcı')),
            ],
            options={
                'verbose_name_plural': '5.1 Forum Beğenmeleri',
            },
        ),
        migrations.CreateModel(
            name='DisLikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_liked', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_comment', to='forums.forumcomment', verbose_name='İlgili Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_comment', to=settings.AUTH_USER_MODEL, verbose_name='Beğenmeyen Kullanıcı')),
            ],
            options={
                'verbose_name_plural': '5.2 Forum Beğenmemeleri',
            },
        ),
    ]
