# Generated by Django 4.1 on 2022-08-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0018_alter_dislikecomment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorSelectForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Gösterilsin mi?')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forum', verbose_name='Seçilecek Forum')),
            ],
            options={
                'verbose_name_plural': '7. Editör Seçimi',
            },
        ),
    ]
