# Generated by Django 4.1 on 2022-08-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0020_userforumpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForumPoint',
        ),
    ]
