# Generated by Django 4.1 on 2022-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_activation',
            field=models.BooleanField(default=False),
        ),
    ]
