# Generated by Django 4.1 on 2022-08-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_userprofile_is_email_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
