# Generated by Django 4.1 on 2022-08-31 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0004_userprofile_service_city_userprofile_work_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveBigIntegerField(verbose_name='Kullanıcı Puanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Puan Alan Kullanıcı')),
            ],
            options={
                'verbose_name_plural': '8. Kullanıcı Puanı',
            },
        ),
    ]
