# Generated by Django 4.1 on 2022-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_userpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpoint',
            options={'verbose_name_plural': '2. Kullanıcı Puanı'},
        ),
        migrations.AddField(
            model_name='userpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
