# Generated by Django 4.1 on 2022-08-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_worktype_alter_citys_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citys',
            options={'ordering': ('id',), 'verbose_name_plural': '1. Şehirler'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ('id',), 'verbose_name_plural': '2. Çalışma Şekilleri'},
        ),
    ]
