# Generated by Django 4.1 on 2022-09-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_banklist_loaninterestrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='banklist',
            name='is_important',
            field=models.BooleanField(default=False, null=True, verbose_name='Anasayfada Gösterilsin Mi?'),
        ),
    ]
