# Generated by Django 4.1 on 2022-09-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_banklist_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninterestrate',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_bank', to='mainpage.banklist', verbose_name='Banka Adı'),
        ),
        migrations.AlterField(
            model_name='loaninterestrate',
            name='state',
            field=models.CharField(choices=[('Arttı', 'Arttı'), ('Azaldı', 'Azaldı'), ('Stabil', 'Stabil')], max_length=50, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.citys', verbose_name='Şehir')),
            ],
            options={
                'verbose_name_plural': '5. Şehir Hava Durumu',
            },
        ),
    ]
