# Generated by Django 4.1 on 2022-09-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_loaninterestrate_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='mainpage.citys', verbose_name='Şehir'),
        ),
    ]
