# Generated by Django 4.1 on 2022-09-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_weather_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='user',
        ),
    ]
