# Generated by Django 4.0.2 on 2022-09-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_newscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Soyisim')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şirket Adı')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Telefon')),
                ('type', models.CharField(choices=[('1', 'Reklam'), ('2', 'Haber'), ('3', 'Çalışan Alımı'), ('4', 'İstek-Öneri'), ('5', 'Şikayet')], max_length=50, null=True, verbose_name='İlan Tipi')),
                ('ads', models.CharField(blank=True, choices=[('1', '1. Kategori'), ('2', '2. Kategori'), ('3', '3. Kategori'), ('4', '4. Kategori'), ('5', '5. Kategori')], max_length=50, null=True, verbose_name='Reklam Kategorisi')),
                ('message', models.TextField(null=True, verbose_name='Mesaj')),
            ],
            options={
                'verbose_name_plural': '7. İlanlar',
            },
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': '6. Haber Kategorileri'},
        ),
    ]
