# Generated by Django 4.0.2 on 2022-09-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_advertisement_alter_newscategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Haber Başlığı'),
        ),
    ]
