# Generated by Django 4.1 on 2022-09-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_advertisement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ilan/', verbose_name='İlan Resimleri'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
