# Generated by Django 4.1 on 2022-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_advertisement_image_advertisement_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(choices=[('1', 'Anasayfa'), ('1', 'İlan')], max_length=100, null=True, verbose_name='Sayfa Seçimi')),
                ('content', models.TextField(null=True, verbose_name='İçerik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '8. Notlar',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
