# Generated by Django 4.0.2 on 2022-09-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_note_advertisement_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='Fiyat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '7.1. Reklam Kategorileri',
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='pages',
            field=models.CharField(choices=[('1', 'Anasayfa'), ('2', 'İlan')], max_length=100, null=True, verbose_name='Sayfa Seçimi'),
        ),
    ]
