# Generated by Django 4.0.2 on 2022-09-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_adscategory_alter_note_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adscategory',
            options={'ordering': ['name'], 'verbose_name_plural': '7.1. Reklam Kategorileri'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.adscategory', verbose_name='Reklam Kategorisi'),
        ),
    ]
