# Generated by Django 4.0.2 on 2022-09-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_alter_adscategory_options_alter_advertisement_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscategory',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
