# Generated by Django 4.0.2 on 2022-09-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_advertisementtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.advertisementtype', verbose_name='İlan Tipi'),
        ),
    ]
