# Generated by Django 4.0.2 on 2022-10-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_alter_advertisement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementtype',
            options={'ordering': ['name'], 'verbose_name_plural': '7.2. İlan Kategorileri'},
        ),
        migrations.CreateModel(
            name='CreateAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Müşteri İsim ve Soyismi')),
                ('email', models.EmailField(max_length=254, verbose_name='Müşteri Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Müşteri Telefon')),
                ('price', models.CharField(max_length=255, verbose_name='Reklam Ücreti')),
                ('image', models.ImageField(blank=True, help_text='1296 px x 100 px boyutlarında olmalıdır.', null=True, upload_to='ilan/reklamlar/', verbose_name='Reklam Resmi')),
                ('link', models.CharField(max_length=1000, null=True, verbose_name='Reklam Linki')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Reklam Başlığı')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_time', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.adscategory', verbose_name='Reklam Kategorisi')),
            ],
            options={
                'verbose_name_plural': '7.3 Oluşturulan Reklamlar',
            },
        ),
    ]
