# Generated by Django 4.0.2 on 2022-08-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroup',
        ),
    ]
