# Generated by Django 4.1 on 2022-08-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_room_group_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name_plural': '2. Grup Üyeleri'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',), 'verbose_name_plural': '3. Mesajlar'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='group_user',
        ),
        migrations.AddField(
            model_name='membership',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.room'),
        ),
    ]
