# Generated by Django 4.1 on 2022-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_membership_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banner',
            field=models.ImageField(null=True, upload_to='kanal/banner'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='kanal/kapak'),
        ),
        migrations.AddField(
            model_name='room',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
