# Generated by Django 4.1 on 2022-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_room_created_at_alter_room_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='kanal/banner'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kanal/kapak'),
        ),
    ]
