# Generated by Django 4.1 on 2022-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
