# Generated by Django 4.1 on 2022-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_membership_joined_date_room_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Güncellendiği Tarih'),
        ),
    ]
