# Generated by Django 4.1 on 2022-08-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_membership_options_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',), 'verbose_name_plural': '3. Kanal Mesajları'},
        ),
    ]
