# Generated by Django 4.1 on 2022-08-23 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0017_message_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Duyuru Başlık')),
                ('content', models.TextField(verbose_name='Duyuru İçeril')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_announcement', to='server.room', verbose_name='Kanal Adı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_announcement', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': '3. Kanal Mesajları',
                'ordering': ('date_added',),
            },
        ),
    ]
