# Generated by Django 4.1 on 2022-08-23 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0018_roomannouncement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomannouncement',
            options={'ordering': ('date_added',), 'verbose_name_plural': '4. Kanal Duyuruları'},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name_plural': '6. Kategoriler'},
        ),
        migrations.CreateModel(
            name='RoomManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Yönetici Olma Tarihi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_manager', to='server.room', verbose_name='Kanal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_manager', to=settings.AUTH_USER_MODEL, verbose_name='Kanal Yöneticileri')),
            ],
            options={
                'verbose_name_plural': '5. Kanal Yöneticileri',
                'ordering': ('date_added',),
            },
        ),
    ]
