# Generated by Django 4.1 on 2022-08-23 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0019_alter_roomannouncement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_message', to='server.message', verbose_name='Favori Mesaj')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_message', to='server.room', verbose_name='Kanal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_message', to=settings.AUTH_USER_MODEL, verbose_name='Favorilere Ekleyen Kullanıcı')),
            ],
            options={
                'verbose_name_plural': '6. Favori Mesajları',
                'ordering': ('date_added',),
            },
        ),
    ]
