# Generated by Django 4.1 on 2022-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(help_text='En fazla 255 karakter', max_length=255, null=True, verbose_name='Kanal Tanımı'),
        ),
    ]
