# Generated by Django 4.1 on 2022-08-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(help_text='En fazla 160 karakter', max_length=160, null=True, verbose_name='Kanal Tanımı'),
        ),
    ]
