# Generated by Django 4.1 on 2022-08-25 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0023_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='group_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_ship', to=settings.AUTH_USER_MODEL, verbose_name='Üye'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_ship', to='server.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=120, null=True, verbose_name='Kanal Adı'),
        ),
    ]
