# Generated by Django 4.1 on 2022-08-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name_plural': '2. Anket Seçenekleri'},
        ),
        migrations.AddField(
            model_name='options',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='İlgili Anket'),
        ),
    ]
