# Generated by Django 4.1 on 2022-08-19 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_alter_options_options_options_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='answered_user',
        ),
        migrations.AddField(
            model_name='options',
            name='options_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seçenek Oluşturan Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='options',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cevap Veren Kullanıcı')),
                ('options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.options', verbose_name='Ankete Ait Seçenekler')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='İlgili Anket')),
            ],
            options={
                'verbose_name_plural': '3. Anket Cevapları',
            },
        ),
    ]
