# Generated by Django 4.1 on 2022-08-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_message_file_type'),
        ('survey', '0003_remove_options_answered_user_options_options_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.room', verbose_name='Oda'),
        ),
    ]
