# Generated by Django 4.1 on 2022-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_answered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
