# Generated by Django 4.0.2 on 2022-08-16 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Bildirim İçeriği')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Görüldü Mü?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_notifications', models.CharField(max_length=100, null=True, verbose_name='Bildirim Kategorisi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'Bildirimler',
            },
        ),
    ]
