# Generated by Django 4.0.2 on 2022-08-16 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Bildirim Gönderilen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Bildirim Gönderen Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(null=True, verbose_name='Bildirim İçeriği'),
        ),
    ]
